name: rppc
channels:
  - conda-forge
dependencies:
  - doctr
  - flake8
  - flake8-builtins
  - flake8-comprehensions
  - flake8-import-order
  - flake8-mutable
  - flake8-print
  - flake8-quotes
  - nbconvert
  - nbsphinx
  - pycodestyle
  - pytest
  - sphinx
  - twine
  - wheel
